version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
     - "6379:6379"
    volumes:
     - redis-data:/data
    networks:
     - postgres-redis-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-redis-network

volumes:
  redis-data:
  pgdata:

networks:
  postgres-redis-network: